version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /elastic-query-service/frontend
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /docker-compose
    schedule:
      interval: weekly
