logging:
  level:
    ROOT: info
    com.microservices.demo: info

spring:
  application:
    name: elastic-query-service
  profiles:
    active: elastic_query
  config:
    import: "configserver:"
  cloud:
    config:
      name: elastic-query-service,config-client
      username: spring_cloud_user
      password: "1234"

  # Zipkin configuration for Spring Boot 3.x
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

# Management endpoints for tracing (Spring Boot 3.x style)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,tracing
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411

# Zipkin reporter configuration
zipkin:
  sender:
    type: kafka

log:
  appName: elastic-query-service
