version: '3.7'  # Can be removed if using newer Docker Compose

services:
  elastic-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    container_name: elastic-1
    environment:
      - node.name=elastic-1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elastic-2,elastic-3
      - cluster.initial_master_nodes=elastic-1,elastic-2,elastic-3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01_7_17_4_new:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  elastic-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    container_name: elastic-2
    environment:
      - node.name=elastic-2
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elastic-1,elastic-3
      - cluster.initial_master_nodes=elastic-1,elastic-2,elastic-3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02_7_17_4_new:/usr/share/elasticsearch/data
    networks:
      - elastic

  elastic-3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    container_name: elastic-3
    environment:
      - node.name=elastic-3
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elastic-1,elastic-2
      - cluster.initial_master_nodes=elastic-1,elastic-2,elastic-3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03_7_17_4_new:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.4
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: '["http://elastic-1:9200"]'
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.4
    container_name: logstash
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - 5000:5000
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - elastic

volumes:
  data01_7_17_4_new:
    driver: local
  data02_7_17_4_new:
    driver: local
  data03_7_17_4_new:
    driver: local

networks:
  elastic:
    driver: bridge