version: '3.7'

services:
  redis-master:
    image: redis:${REDIS_VERSION:-latest}
    hostname: redis-master
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - redis-network

  redis-slave:
    image: redis:${REDIS_VERSION:-latest}
    command: ["redis-server", "--slaveof", "redis-master", "6379"]
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge