server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Solano204/spring-cloud-config-server-repository
          default-label: main
          username: Solano204
          password: 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
          clone-on-start: true
      fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: '1234'

# Use environment variable for encryption key
encrypt:
  key: ${ENCRYPT_KEY:defaultEncryptionKey123}

log:
  app-name: config-server

